### PR TITLE
Add multipass check and install into setupLinux.sh.

### PR DESCRIPTION
**Pull request by DevinBeu**
Add multipass to machine if it is not installed.

### CODE REVIEW

**Review by jlotto8 — APPROVED** [review]
perfect

**Comment by MonetCarriere** [comment]
Looks Good

**Review by MonetCarriere — APPROVED** [review]
Good Job

**Review by stephenlauck — APPROVED** [review]
:ship:

**Review by whmcquaid — APPROVED** [review]
:shipit:

**Pull request merged**
